name: game_assignment
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.2
  flame: 1.3.0
  flame_tiled: 1.7.2
  tiled: 0.8.4
  flame_audio: 1.3.1
  flutter_bloc: ^8.0.1
  hive: 2.2.3


dev_dependencies:
  hive_generator: 1.1.3
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/tiles/
